#!/bin/bash

set -e
set -o pipefail

PATH=".:$PATH:./conversion"

ifa=$1
ifb=$2
ofn=$3

if [ "$ifa" == "" ] || [ "$ifb" == "" ] || [ ! -e "$ifa" ] || [ ! -e "$ifb" ] ; then
  echo "provide input_a and input_b"
  exit 1
fi

if [ "$ofn" == "" ] ; then
  ofn="/dev/stdout"
fi

trap "echo ERROR" ERR

echo "#$ifa" > $ofn
echo "#$ifb" >> $ofn
echo "#score,yeslink,nolink,nclink" >> $ofn
concordance.pl <( convert_to_gff.py -i $ifa ) <( convert_to_gff.py -i $ifb ) >> $ofn
