#!/bin/bash

set -eo pipefail

PRODUCTION=0

if [ "$PRODUCTION" == 0 ] ; then
  CRUNCH_SRC=`pwd`/..
fi

export PATH=$PATH:.:..:$CRUNCH_SRC:$CRUNCH_SRC/crunch_scripts:$CRUNCH_SRC/crunch_scripts/bin:$CRUNCH_SRC/conversion

if [ "$PRODUCTION" == 1 ] ; then
. <( arv-dax setup )
fi


mkdir -p tmp
mkdir -p tmp.concordance

mntdir=`pwd`/"../tests"
n=2

if [ "$PRODUCTION" == 1 ] ; then

mntdir=`arv-dax keep`
jobparam=`arv-dax script_parameters`
verbose=`echo "$jobparam" | jq -r '.VERBOSE_FLAG'`
echo "$jobparam" | jq -r '.SET_A[]' > tmp/seta
echo "$jobparam" | jq -r '.SET_B[]' > tmp/setb
n=`echo "$jobparam" | jq -r '.N_PER_CORE'`

else

  ls ../tests/* > tmp/seta
  ls ../tests/* > tmp/setb

fi

rm -f tmp/set_ab

count=0
while read a_fn ; do
  while read b_fn ; do
    echo "$mntdir/$a_fn" >> tmp/set_ab
    echo "$mntdir/$b_fn" >> tmp/set_ab
    echo tmp.concordance/"$count" >> tmp/set_ab
    count=`expr $count + 1`
  done < tmp/setb
done < tmp/seta

cat tmp/set_ab | tr '\n' '\0' | xargs -0 -n3 --max-procs=$n $CRUNCH_SRC/concordance
#cat tmp/set_ab | tr '\n' '\0' | xargs -0 -L1 -n3 --max-procs=$n echo ">>"


collect-results tmp.concordance

#rm -rf tmp.concordance
#rm -rf tmp


if [ "$PRODUCTION" == 1 ] ; then
arv-dax task finish
exit 0
fi

