#!/bin/bash

set -eo pipefail

PRODUCTION=1

if [ "$PRODUCTION" == 0 ] ; then
  CRUNCH_SRC=`pwd`/..
fi

export PATH=$PATH:.:..:$CRUNCH_SRC:$CRUNCH_SRC/crunch_scripts:$CRUNCH_SRC/crunch_scripts/bin:$CRUNCH_SRC/conversion

if [ "$PRODUCTION" == 1 ] ; then
. <( arv-dax setup )
fi


mkdir -p pairwise-concordance

mntdir=`pwd`/"../tests"
n=2

if [ "$PRODUCTION" == 1 ] ; then

  mntdir=`arv-dax keep`
  jobparam=`arv-dax script_parameters`
  verbose=`echo "$jobparam" | jq -r '.VERBOSE_FLAG'`
  afile=`echo "$jobparam" | jq -r '.A' `
  bfile=`echo "$jobparam" | jq -r '.B'`

else

  afile=`ls ../tests/* | head -n1`
  bfile=`ls ../tests/* | head -n1`

fi


$CRUNCH_SRC/concordance "$afile" "$bfile" pairwise-concordance/concordance.csv

collect-results pairwise-concordance

if [ "$PRODUCTION" == 1 ] ; then
  arv-dax task finish
fi

exit 0
