#!/bin/bash
#
# Crunch script to run concordance on a single pair
# of samples.
#


set -eo pipefail

PRODUCTION=1
VERBOSE=1

if [ "$PRODUCTION" == 0 ] ; then
  CRUNCH_SRC=`pwd`
fi

export PATH=$PATH:.:..:$CRUNCH_SRC:$CRUNCH_SRC/crunch_scripts:$CRUNCH_SRC/crunch_scripts/bin:$CRUNCH_SRC/conversion

if [ "$PRODUCTION" == 1 ] ; then
. <( arv-dax setup )
fi


mkdir -p pairwise-concordance

if [ "$PRODUCTION" == 1 ] ; then

  mntdir=`arv-dax keep`
  jobparam=`arv-dax script_parameters`
  verbose=`echo "$jobparam" | jq -r '.VERBOSE_FLAG'`
  afile=$mntdir/`echo "$jobparam" | jq -r '.A' `
  bfile=$mntdir/`echo "$jobparam" | jq -r '.B'`

else

  afile=`ls ./tests/* | head -n1`
  bfile=`ls ./tests/* | head -n1`

fi

if [ "$VERBOSE" == 1 ] ; then
  echo "PATH >>>>>>>>>>>> $PATH"
  echo "afile >>>>>>>>>>>>>>>>> $afile"
  echo "bfile >>>>>>>>>>>>>>>>> $bfile"
  echo `ls $CRUNCH_SRC/concordance`
  echo `ls -lad pairwise-concordance`
  echo "head $afile ***********************"
  echo `head $afile`
  echo "head <( bzcat $bfile ) *******************"
  echo `head <( bzcat $bfile )`

fi


$CRUNCH_SRC/concordance "$afile" "$bfile" pairwise-concordance/concordance.csv

collect-results pairwise-concordance

if [ "$PRODUCTION" == 1 ] ; then
  arv-dax task finish
fi

exit 0
